drop  table chnl_self_trade;
create table chnl_self_trade(
	tx_date number(9),
	tx_time number(9),
	trace_no number(9),
	cur_no varchar2(2),
	ac_no varchar2(20),
	ac_no1 varchar2(20),
	tx_code varchar2(4),
	tx_br_no varchar2(5),
	opn_br_no varchar2(5),
	tel varchar2(4),
	ttyp varchar2(1),
	ttyn varchar2(20),
	sh_opn_br_no varchar2(5),
	spcd varchar2(20),
	bbmk varchar2(4),
	sctp varchar2(2),
	dz_date number(9),
	stra number(9),
	strb number(9),
	premise_date number(9),
	premise_no number(9),
	premise_amt number(16,2),
	tx_amt number(16,2),
	sl_sxamt number(16,2),
	fk_sxamt number(16,2),
	dz_sxamt number(16,2),
	dz_flag varchar2(1),
	ct_ind varchar2(1),
	info_source varchar2(1),
	deal_flag varchar2(1),
	brf_no varchar2(5),
	add_ind varchar2(1),
	batch_flag varchar2(1),
	stat varchar2(1), 
	brf_dscp varchar2(50),
	tt_no varchar2(4)
)tablespace users;
create index chnl_self_trade_1 on chnl_self_trade( dz_date,stra)tablespace indx;
create index chnl_self_trade_2 on chnl_self_trade( dz_date,stra,tx_amt)tablespace indx;
