drop index gl_mst_nj_1;
drop  table gl_mst_nj;
create table gl_mst_nj(
	br_no varchar2(5),
	cur_no varchar2(2),
	acc_hrt varchar2(5),
	"date" number(9),
	dc_ind varchar2(1),
	up_acc_hrt varchar2(5),
	dr_bal number(16,2),
	cr_bal number(16,2),
	ldd_bal number(16,2),
	lcd_bal number(16,2),
	rdd_cnt number(9),
	rcd_cnt number(9),
	rdd_amt number(16,2),
	rcd_amt number(16,2),
	cdd_cnt number(9),
	ccd_cnt number(9),
	cdd_amt number(16,2),
	ccd_amt number(16,2),
	tddr_bal number(16,2),
	tdcr_bal number(16,2),
	tddr_cnt number(9),
	tdcr_cnt number(9),
	tddr_amt number(16,2),
	tdcr_amt number(16,2),
	mdr_bal number(16,2),
	mcr_bal number(16,2),
	mdr_cnt number(9),
	mcr_cnt number(9),
	mdr_amt number(16,2),
	mcr_amt number(16,2),
	qdr_bal number(16,2),
	qcr_bal number(16,2),
	qdr_cnt number(9),
	qcr_cnt number(9),
	qdr_amt number(16,2),
	qcr_amt number(16,2),
	ydr_bal number(16,2),
	ycr_bal number(16,2),
	ydr_cnt number(9),
	ycr_cnt number(9),
	ydr_amt number(16,2),
	ycr_amt number(16,2) 
)tablespace users;
create	 unique index gl_mst_nj_1 on gl_mst_nj( br_no,cur_no,acc_hrt)tablespace indx;
