drop  table in_mst_hst;
create table in_mst_hst(
	trace_no number(9),
	trace_cnt number(9),
	opn_br_no varchar2(5),
	tx_br_no varchar2(5),
	tx_code varchar2(4),
	sub_tx_code varchar2(4),
	tx_date number(9),
	tx_time number(9),
	ac_id number(9),
	ac_seqn number(6),
	add_ind varchar2(1),
	ct_ind varchar2(1),
	tx_amt number(16,2),
	bal number(16,2),
	intst_acm number(19,2),
	note_type varchar2(3),
	note_no varchar2(16),
	brf varchar2(20),
	hst_cnt number(9),
	tel varchar2(4),
	chk varchar2(4),
	auth varchar2(4) 
)tablespace users;
