drop index mbferltxdclt_idx;
drop  table mbferltxdclt;
create table mbferltxdclt(
	consigndate number(9),
	bankcode varchar2(12),
	txsbatno number(9),
	oprttype varchar2(3),
	txssno varchar2(8),
	amount number(15,2),
	osdficodeccpc varchar2(4),
	osdficode varchar2(12),
	payeracc varchar2(32),
	payername varchar2(60),
	payerbnk varchar2(12),
	isdficodeccpc varchar2(4),
	isdficode varchar2(12),
	recipientacc varchar2(32),
	recipientname varchar2(60),
	recipientbnk varchar2(12),
	bondcode varchar2(12),
	bondamount number(18,2),
	setamount number(18,2),
	setdate number(9),
	setrate number(18,2),
	bondordercode varchar2(9),
	netamount number(15,2),
	bondrate number(15,2),
	procstate varchar2(2),
	checkstate varchar2(2),
	statetime varchar2(14),
	printno number(9),
	flowno number(9),
	errcode varchar2(8),
	errdesc varchar2(60),
	oprtsource varchar2(2),
	strinfo varchar2(60) 
)tablespace users;
create	 unique index mbferltxdclt_idx on mbferltxdclt( consigndate,bankcode,txssno)tablespace indx;
