drop index mbfeghvrecvlis_ix1;
drop index mbfeghvrecvlis_ix2;
drop  table mbfeghvrecvlist;
create table mbfeghvrecvlist(
	txssno varchar2(8),
	consigndate number(9),
	cmtno varchar2(3),
	amount number(15,2),
	odficode varchar2(12),
	isdficode varchar2(12),
	odficenter varchar2(4),
	payeropenaccbkcode varchar2(12),
	payeracc varchar2(32),
	payername varchar2(60),
	payeraddr varchar2(60),
	cnapsrdfi varchar2(12),
	rdficode varchar2(12),
	osdficode varchar2(12),
	rdficenter varchar2(4),
	recipientopenaccbk varchar2(12),
	recipientacc varchar2(32),
	recipientname varchar2(60),
	recipientaddr varchar2(60),
	oprttype varchar2(2),
	warrantdate number(9),
	warrantno varchar2(8),
	compensationamnt number(18,4),
	repudiationamnt number(15,2),
	prmptpaydate number(9),
	prilevel varchar2(1),
	printno number(9),
	procstate varchar2(2),
	hang_reply varchar2(4),
	statetime varchar2(14),
	rectime varchar2(14),
	billofxchngseal varchar2(10),
	checkstate varchar2(2),
	flowno number(9),
	incomeacno varchar2(24),
	incomebkcode varchar2(12),
	incometime varchar2(14),
	incomeflowno number(9),
	incometel varchar2(4),
	strinfo varchar2(60),
	content varchar2(100) 
)tablespace users;
create	 unique index mbfeghvrecvlis_ix1 on mbfeghvrecvlist( consigndate,txssno,odficode)tablespace indx;
create	 index mbfeghvrecvlis_ix2 on mbfeghvrecvlist( consigndate,flowno)tablespace indx;
