#ifndef __trace_log_CH__
#define __trace_log_CH__
struct trace_log_c{
	char      rowid[20];
	long      trace_no;
	long      trace_cnt;
	long      tx_date;
	long      tx_time;
	char      tx_br_no[6];
	char      opn_br_no[6];
	char      tx_code[5];
	char      sub_tx_code[5];
	long      svc_ind;
	char      cur_no[3];
	char      prdt_no[4];
	char      ac_no[20];
	long      ac_seqn;
	long      ac_id;
	char      note_type[4];
	char      note_no[17];
	char      add_ind[2];
	double    amt;
	char      ct_ind[2];
	char      brf[21];
	char      tel[5];
	char      chk[5];
	char      aut[5];
	char      hst_ind[2];
	char      saving_notarize[2];
	char      no_show[2];
	char      sts[2];
	char      stat[2];
};
#endif 
