/*MBFE接口交易结构*/
struct			MBFETRAN
{
char			msssno[9];					/*信息序号*/
char			procstate[3];				/*处理状态*/
char			cmtno[4];					/*CMT号码*/
char			origcmtno[4];				/*原CMT编号*/
char			prilevel[2];				/*优先级别*/
char			msgno[9];					/*报文标识号*/
char			respno[21];					/*报文参考号*/
char			rectime[15];				/*来帐收到时间*/
char			sendtime[15];				/*发送时间*/
char			oper_syscode[4];			/*业务状态码*/
char			rtnappno[4];				/*申请号（退回/撤销）*/
char			origrtnappno[4];			/*原申请号（撤销/退回）*/
char			txtype[2];					/*交易种类*/
char			origtxtype[2];				/*原交易种类*/
char			cmtnolist[89];				/*CMT号码列表*/
char			number[5];					/*数目*/
char			datatype[4];				/*数据类型*/
char			*updcntt;					/*更新内容*/
char			srflag[2];					/*往来标识*/
char			dcflag[2];					/*借贷标识*/
char			consigndate[9];				/*委托日期*/
char			prmptpaydate[9];			/*提示付款日期*/
char			querydate[9];				/*查询日期*/
char			rplydate[9];				/*查复日期*/
char			origconsigndate[9];			/*原委托日期*/
char			origquerydate[9];			/*原查询日期*/
char			origrtnappdate[9];			/*原退回申请日期*/
char			origsyswkdate[9];			/*原系统工作日*/
char			currsyswkdate[9];			/*当前系统工作日*/
char			t1_syswkdate[9];			/*T+1系统工作日*/
char			t2_syswkdate[9];			/*T+2系统工作日*/
char			wrkdate[9];					/*工作日期（CNAPS当前工作日）*/
char			setdate[9];					/*回购到期日*/
char			notepaydate[9];				/*提示付款日期*/
char			feebgdate[9];				/*计费开始日期*/
char			feeeddate[9];				/*计费终止日期*/
char			feeammunt[16];				/*收费金额或计费总金额*/
char			sapsrate[7];				/*直接参与者收费比率*/
char			bktprate[7];				/*行别收费比率*/
char			mothrate[7];				/*月累计业务量收费比率*/
char			hvpfeeamt[16];				/*支付类业务收费金额*/
char			hvpfeecnt[9];				/*支付类业务收费记录个数*/
char			*hvpfeedetail;				/*支付类业务收费明细*/
char			singlefeeamt[16];			/*单边业务收费金额*/
char			singlefeecnt[9];			/*单边业务收费记录个数*/
char			*singlefeedetail;			/*单边业务收费明细*/
char			infofeeamt[16];				/*信息类业务收费金额*/
char			infofeecnt[9];				/*信息类业务收费记录个数*/
char			*infofeedetail;				/*信息类业务收费明细*/
char			sndcmtcentrecvtime[15];		/*发报中心接收时间*/
char			sndcmtcentmvtime[15];		/*发报中心转发时间*/
char			recvcmtcentrecvtime[15];	/*收报中心接收时间*/
char			recvcmtcentmvtime[15];		/*收报中心转发时间*/
char			npcrecvtime[15];			/*NPC接收时间*/
char			sapclrtime[15];				/*SAP清算时间*/
char			npcmvtime[15];				/*NPC转发时间*/
char			statetime[15];				/*处理/更新时间*/
char			npctranstat[3];				/*NPC交易状态*/
char			sndcmtcenttranstat[3];		/*发报中心交易状态*/
char			recvcmtcenttranstat[3];		/*收报中心交易状态*/
char			currsysstat[3];				/*当前系统状态*/
char			origsysstat[3];				/*原系统状态*/
char			querymsgno[9];				/*查询书号*/
char			origquerymsgno[9];			/*原查询书号*/
char			rplymsgno[9];				/*查复书号*/
char			moneysymb[4];				/*货币符号*/
char			amount[16];					/*金额*/
char			origamount[16];				/*原金额*/
char			accrualamnt[23];			/*透支利息合计*/
char			*accrualinfo;				/*计息信息*/
char			netamount[16];				/*净价金额*/
char			bondrate[16];				/*债券利息*/
char			bondamount[19];				/*债券面额*/
char			setamount[19];				/*回购首期结算额*/
char			setrate[16];				/*回购利息*/
char			billtype[2];				/*汇票类别*/
char			billofxchngseal[11];		/*汇票密押*/
char			remittanceamnt[16];			/*出票金额*/
char			factclramnt[16];			/*实际结算金额*/
char			redundantamnt[16];			/*多余金额*/
char			lastbillholderacc[33];		/*最后持票人账号*/
char			lastbillholdername[61];		/*最后持票人名称*/
char			otxtotalcnt[11];			/*往账总笔数*/
char			otxtotalamnt[23];			/*往账总金额*/
char			otxsortnum[3];				/*往账分类项目数*/
char			otxsortinfo[353];			/*往账分类汇总信息*/
char			itxtotalcnt[11];			/*来账总笔数*/
char			itxtotalamnt[23];			/*来账总金额*/
char			itxsortnum[3];				/*来账分类项目数*/
char			itxsortinfo[353];			/*来账分类汇总信息*/
char			immtrasortnum[3];			/*即时转账分类项目数*/
char			immtrasortinfo[193];		/*即时转账分类汇总信息*/
char			finaamt[16];				/*融资本金*/
char			finarest[16];				/*融资利息*/
char			osdficodeccpc[5];			/*被借记行所在CCPC代码*/
char			isdficodeccpc[5];			/*被贷记行所在CCPC代码*/
char			ccpcbkno[13];				/*CCPC号（或银行行号、特许参与者号）*/
char			rtnrplybkcode[13];			/*退回行行号*/
char			requcelbkno[13];			/*申请撤销行行号*/
char			querybkcode[13];			/*查询行行号*/
char			origquerybkcode[13];		/*原查询行行号*/
char			origqueryisdficode[13];		/*原查询清算行行号*/
char			rplybkcode[13];				/*查复行行号*/
char			odficenter[5];				/*发报中心代码*/
char			isdficode[13];				/*发起清算行行号*/
char			odficode[13];				/*特许参与者/发起行行号*/
char			cnapsodfi[13];				/*支付发起行行号*/
char			rdficenter[5];				/*收报中心代码*/
char			osdficode[13];				/*接收清算行行号*/
char			rdficode[13];				/*接收行行号*/
char			cnapsrdfi[13];				/*支付接收行行号*/
char			origodficode[13];			/*原发起行行号*/
char			payeropenaccbkcode[13];		/*付款人开户行行号*/
char			payeracc[33];				/*付款人账号*/
char			payername[61];				/*付款人名称*/
char			payeraddr[61];				/*付款人地址*/
char			recipientopenaccbk[13];		/*收款人开户行行号*/
char			recipientacc[33];			/*收款人账号*/
char			recipientname[61];			/*收款人名称*/
char			recipientaddr[61];			/*收款人地址*/
char			origpayeracc[33];			/*原付款人帐号*/
char			origpayername[61];			/*原付款人名称*/
char			origrdficode[13];			/*原接收行行号/原指定兑付行行号*/
char			origrecipientacc[33];		/*原收款人帐号*/
char			origrecipientname[61];		/*原收款人名称*/
char			oprttype3[3];				/*业务种类3*/
char			oprttype2[4];				/*业务种类2*/
char			warrantdate[9];				/*票据日期*/
char			warrantno[9];				/*票据号码*/
char			notetype[3];				/*凭证种类*/
char			noteno[9];					/*凭证号码*/
char			compensationamnt[16];		/*赔偿金金额*/
char			rmlnrate[16];				/*拆借利率*/
char			repudiationamnt[16];		/*拒付金额*/
char			rmlnlimit[6];				/*拆借期限*/
char			txssno[9];					/*支付交易序号*/
char			origtxssno[9];				/*原支付交易序号*/
char			strinfo[61];				/*附言*/
char			cancelresult[2];			/*撤销应答*/
char			rtnrplyrus[2];				/*退回应答*/
char			errcode[9];					/*处理码*/
char			errdesc[61];				/*处理描述*/
char			querycntt[256];				/*内容（查询、查复、自由格式内容）*/
char			itxlendcnt[11];				/*来帐借记总笔数*/
char			itxloancnt[11];				/*来帐贷记总笔数*/
char			otxlendcnt[11];				/*往帐借记总笔数*/
char			otxloancnt[11];				/*往帐贷记总笔数*/
char			filename[51];				/*文件名*/
char			filename_cmt[51];			/*来报文件名*/
char			modtype[2];					/*变更类型*/
char			txsbatno[7];				/*交易批次*/
char			bondcode[13];				/*债券代码*/
char			bondordercode[10];			/*债券结算已匹配指令号*/
};
