#ifndef __cupsppfw_CH__
#define __cupsppfw_CH__
struct cupsppfw_c{
	char      rowid[20];
	char      brtype[2];
	char      filename[31];
	char      txday[9];
	char      brno[9];
	char      firstbr[12];
	char      cardtype[2];
	char      cdtype[2];
	char      jyqd[3];
	char      cardjz[2];
	char      outtxfg[2];
	char      mertype[5];
	char      secbr[12];
	char      dlbrno[33];
	char      fsbrno[33];
	char      opnbrno[12];
	char      isbkno[12];
	char      sdbrno[12];
	char      msgtype[5];
	char      txcode[7];
	char      inputcd[3];
	char      trseq[12];
	char      txtime[11];
	char      cardno[20];
	char      outcardno[20];
	char      incardno[20];
	char      otxmsg[43];
	char      atmno[9];
	char      acbkflg[16];
	char      wssrno[13];
	double    txamt;
	double    slfee;
	double    pinpfee;
	double    jamt;
	char      tmp1[13];
	char      tmp2[101];
};
#endif 
