#ifndef __hv_chkagehtr_CH__
#define __hv_chkagehtr_CH__
struct hv_chkagehtr_c{
	char      rowid[20];
	char      orderno[9];
	char      pay_qs_no[13];
	long      tx_date;
	char      br_no[8];
	char      cmtno[4];
	long      tx_time;
	char      cur_no[4];
	double    tx_amt;
	char      or_br_no[13];
	char      pay_no[13];
	char      pay_ac_no[33];
	char      pay_name[61];
	char      cash_qs_ac_no[13];
	char      acbr_no[13];
	char      cash_no[13];
	char      cash_ac_no[33];
	char      cash_name[61];
	char      yw_type[3];
	char      sendco[5];
	char      receco[5];
	char      operlevel[2];
	char      brf1[31];
	char      brf2[31];
};
#endif 
