#ifndef __lv_c254r_CH__
#define __lv_c254r_CH__
struct lv_c254r_c{
	char      rowid[20];
	char      cmtno[4];
	long      in_date;
	long      wt_date;
	long      dtlid;
	char      o_pkgno[4];
	long      o_wtdate;
	char      o_pay_qs_no[13];
	char      zc_type[2];
	char      zc_node[2];
	long      zc_date;
	char      zc_id[9];
	char      crdb[2];
	double    zc_amt;
	char      o_packid[9];
	long      qs_date;
	char      qs_sts[2];
	char      tx_time[15];
	char      brno[8];
	char      tel[7];
	char      tr_ac_no[7];
	char      sts[2];
	char      brprt_flg[65];
	char      qsprt_flg[65];
	char      filler[61];
};
#endif 
