#ifndef __march_mst_hst_CH__
#define __march_mst_hst_CH__
struct march_mst_hst_c{
	char      rowid[20];
	char      area_code[5];
	char      march_code[16];
	char      ac_no[21];
	char      mch_name[41];
	long      tx_date;
	long      tx_cnt;
	double    tx_amt;
	double    fee_amt;
	double    fee_rate;
	double    real_amt;
	long      acct_date;
	char      deal_sign[2];
	char      deal_msg[41];
	char      opn_br_no[6];
	long      cz_pt_trace_no;
	long      cz_pt_date;
	char      xf_ac_no[25];
	long      trace_no;
	long      pt_trace_no;
	long      pt_date;
	char      dc_ind[2];
	char      cz_ind[2];
	char      ysq_ind[2];
	char      cx_ind[2];
};
#endif 
