#ifndef __mo_finance_quit_CH__
#define __mo_finance_quit_CH__
struct mo_finance_quit_c{
	char      rowid[20];
	long      trace_no;
	long      trace_cnt;
	long      mid_trace_no;
	char      tx_br_no[6];
	char      tx_code[5];
	long      tx_date;
	long      tx_time;
	char      untread_no[21];
	char      untread_stat[11];
	char      pay_no[21];
	long      untread_date;
	char      ct_ind[2];
	char      payee_name[51];
	char      payee_acno[25];
	char      payee_brno[51];
	char      payer_name[51];
	char      payer_acno[25];
	char      payer_brno[51];
	char      item_code[6];
	char      unit_code[17];
	double    amt;
	char      untread_cause[101];
	char      brf[21];
	char      tel[5];
	char      chk[5];
	char      auth[5];
};
#endif 
