#ifndef __mo_finance_info_CH__
#define __mo_finance_info_CH__
struct mo_finance_info_c{
	char      rowid[20];
	long      trace_no;
	long      trace_cnt;
	long      mid_trace_no;
	char      tx_br_no[6];
	char      tx_code[5];
	long      tx_date;
	long      tx_time;
	char      pay_no[21];
	char      agent_bank[4];
	char      agent_br_no[6];
	char      hall_code[4];
	char      unit_code[17];
	long      ticket_date;
	char      pay_sign[4];
	char      ct_ind[2];
	char      payer_name[51];
	char      payer_acno[25];
	char      payer_brno[51];
	char      payer_sort[2];
	char      payee_name[51];
	char      payee_acno[25];
	char      payee_brno[51];
	double    amt;
	char      validate_code[6];
	char      sts[2];
	char      brf[21];
	char      tel[5];
	char      chk[5];
	char      auth[5];
};
#endif 
