#ifndef __mo_int_tax_hst_CH__
#define __mo_int_tax_hst_CH__
struct mo_int_tax_hst_c{
	char      rowid[20];
	char      ac_no[20];
	long      ac_id;
	long      ac_seqn;
	char      tx_code[5];
	char      tx_br_no[8];
	long      tx_date;
	long      tx_time;
	long      trace_no;
	long      trace_cnt;
	long      beg_date;
	long      end_date;
	double    tx_amt;
	double    tx_tax_amt;
	double    intst_acm;
	double    tot_intst_acm;
	double    rate;
	double    intst;
	double    intst_tax_rate;
	double    intst_tax;
	char      brf[21];
	char      tel[7];
	char      sts[2];
	char      filler[31];
};
#endif 
