#ifndef __mob_acct_type_hst_CH__
#define __mob_acct_type_hst_CH__
struct mob_acct_type_hst_c{
	char      rowid[20];
	char      ac_no[21];
	long      ac_id;
	long      ac_seqn;
	char      ac_type[2];
	char      server_type[5];
	char      mobile[13];
	long      ori_tx_date;
	long      lst_fee_date;
	char      lst_tel[5];
	char      sfbz[2];
	char      mob_sts[2];
	char      phones[61];
	char      lst_br_no[6];
	char      filler[51];
	long      tx_date;
	char      tx_code[5];
	long      trace_no;
	char      opr_sts[2];
	char      br_no[6];
	char      tx_tel[7];
	char      new_ac_no[31];
	char      new_mobile[51];
	double    fee;
	char      auth_tel[7];
	char      filler1[16];
	char      filler2[21];
	char      filler3[31];
	char      filler4[51];
	char      filler5[51];
	char      filler6[51];
	char      memo[101];
	char      sts[2];
};
#endif 
