#ifndef __td_mst_CH__
#define __td_mst_CH__
struct td_mst_c{
	char      rowid[20];
	long      ac_id;
	long      ac_seqn;
	char      opn_br_no[6];
	char      prdt_no[4];
	double    bal;
	double    acbo_bal;
	double    ys_bal;
	double    hst_bal;
	double    rate;
	double    flt_ratio;
	double    intst_acm;
	char      intst_type[2];
	long      opn_date;
	long      ic_date;
	long      mtr_date;
	long      lst_date;
	double    td_amt;
	long      ttl_cnt;
	long      tx_cnt;
	long      hst_cnt;
	char      odtt_ind[2];
	char      ac_sts[2];
	char      hold_sts[2];
	double    hold_amt;
	double    ctl_amt;
	char      tfr_ind[2];
	long      cif_no;
	char      name[61];
	char      cal_code[11];
	long      book_line;
	char      mac[17];
};
#endif 
