#ifndef __weixin_acct_hst_CH__
#define __weixin_acct_hst_CH__
struct weixin_acct_hst_c{
	char      rowid[20];
	long      pt_trace_no;
	long      acct_date;
	char      bussi_name[61];
	char      bussi_ac_no[21];
	char      opn_br_no[61];
	char      br_name[61];
	char      tx_type[61];
	long      tx_cnt;
	double    tx_amt;
	long      refud_cnt;
	double    refud_amt;
	double    retan_amt;
	double    bussi_rate;
	double    bussi_chrg;
	double    wx_chrg;
	double    bk_amt;
	double    wft_chrg;
	double    tx_bk_chrg;
	double    bussi_amt;
	long      hx_trace_no;
	char      sts[2];
	char      filename[51];
	char      filler1[31];
	char      filler2[31];
	char      key1[17];
	char      key2[17];
};
#endif 
