#ifndef __zjgl_mst_CH__
#define __zjgl_mst_CH__
struct zjgl_mst_c{
	char      rowid[20];
	char      opn_br_no[6];
	char      cur_no[3];
	char      acc_no[8];
	char      acc_hrt[6];
	double    dr_bal;
	double    cr_bal;
	double    ys_dr_bal;
	double    ys_cr_bal;
	char      sts[2];
	long      opn_date;
	long      ic_date;
	long      end_date;
	long      cls_date;
	long      lst_date;
	char      intst_knd[11];
	char      over_rate_type[4];
	char      rate_type[4];
	double    rate;
	double    over_rate;
	double    dr_intst_acm;
	double    cr_intst_acm;
	long      hst_cnt;
	long      hst_pg;
	char      od_ind[2];
	char      name[51];
	double    lim_amt;
	double    lim_bal;
	char      lim_term[3];
	long      lim_beg_date;
	long      lim_end_date;
	char      tmp1[51];
	char      tmp2[51];
	double    tmp_amt1;
	double    tmp_amt2;
};
#endif 
