CC	=	cc $(Q64) -g
RM	=	rm	-f
MV	=	mv
CP	=	cp

BIN = $(HOME)/bin
LIBDIR = $(HOME)/lib

INC = -I$(HOME)/src/incl_c -I$(HOME)/src/incl_pub
LIB = -L$(HOME)/lib
CFLAGS = $(INC) $(LIB)

#LIBAPL = $(LIB) -lacct -lcard -leod -lpubdb -lsttl -lagent -lcif -lln \
#	-lpubdb_m -lass  -lcom -lrept -lbase -lde  -lod  -lrpt  -lhv
LIBAPL = $(LIB) -lacct -lcard -leod -lpubdb -lsttl -lagent -lcif -lln \
	-lpubdb_m -lass  -lcom -lrept -lbase -lde  -lod  -lrpt

OBJS   = spJ001.so spJ007.so spJ013.so spJ019.so spJ025.so spJ418.so spJ998.so spWYTJ.so\
	 spJ002.so spJ008.so spJ014.so spJ020.so spJ026.so spJ086.so spJ302.so spJ610.so spJ999.so \
 	 spJ003.so spJ009.so spJ015.so spJ021.so spJ027.so spJ090.so spJ312.so spJ620.so spJ841.so spJAAA.so \
	 spHPSP.so spJ004.so spJ010.so spJ016.so spJ022.so spJ028.so spJ091.so spJ314.so spJ689.so spJ910.so spJBBB.so \
 	 spJ000.so spJ005.so spJ011.so spJ017.so spJ023.so spJ069.so spJ123.so spJ408.so spJ690.so spJ911.so spJLZ1.so \
	 spJ0001.so spJ006.so spJ012.so spJ018.so spJ024.so spJ081.so spJ232.so spJ417.so spJ725.so spJ912.so spPARM.so

#spJ082.so spJ253.so spJ802.so spJ803.so




		
TARGET = $(BIN)/lib.so

all: $(TARGET)

$(TARGET):$(OBJS)

.SUFFIXES: .so .c

.c.so:
	$(CC) $(CFLAGS) -c $*.c
	$(CC) -G -o $@ $(CFLAGS) $*.o $(LIBAPL)
	cp $(*F).so $(LIBDIR)
	$(RM) $(*F).o
	$(RM) $(*F).so

.c:
	$(CC) -G -o $@ $(CFLAGS) $*.c $(LIBAPL)
	cp *.so $(LIBDIR)
