#ifndef __card_check_sheet_CH__
#define __card_check_sheet_CH__
struct card_check_sheet_c{
        char      rowid[20];
        char      proxy_br_no[12];
        char      sys_traceno[7];
        char      tx_time[11];
        char      ac_no[20];
        char      tx_amt[13];
        char      pack_type[5];
        char      tx_type[7];
        char      merch_type[5];
        char      term_no[9];
        char      retrive_refno[13];
        char      serv_cond_no[3];
        char      auth_resp_no[7];
        char      recv_br_no[12];
        char      old_sys_traceno[7];
        char      old_tx_time[11];
        char      tx_resp_code[3];
        char      input_mode[4];
        char      get_fee[13];
        char      pay_fee[13];
        char      trans_serv_fee[13];
        char      cardholder_fee[13];
        char      err_get_fee[13];
        char      err_pay_fee[13];
        char      err_tx_flg[4];
        char      transout_brno[12];
        char      transout_cardno[20];
        char      transin_brno[12];
        char      transin_cardno[20];
        char      card_serial_no[4];
        char      term_capbility[2];
        char      card_cond_code[2];
        char      place_flg[2];
        char      tx_start_chnl[3];
        char      reserved[21];
};
#endif 
