#ifndef __cash_mst_hst_CH__
#define __cash_mst_hst_CH__
struct cash_mst_hst_c{
	char      rowid[20];
	long      trace_no;
	long      trace_cnt;
	char      br_no[6];
	char      ac_no[11];
	char      tel[5];
	char      cur_no[3];
	char      add_ind[2];
	char      tw_ac_no[25];
	double    amt;
	long      tx_date;
	long      tx_time;
	char      brf[21];
	long      t10000;
	long      t5000;
	long      t2000;
	long      t1000;
	long      t500;
	long      t200;
	long      t100;
	long      t50;
	long      t20;
	long      t10;
	long      t5;
	long      t2;
	long      t1;
	char      cash_code[21];
};
#endif 
