#ifndef __chnl_compare_acct_CH__
#define __chnl_compare_acct_CH__
struct chnl_compare_acct_c{
	char      rowid[20];
	long      detail_no;
	char      un_marking[33];
	char      syscode[6];
	char      com_date[10];
	char      code_type[7];
	char      wt_date[10];
	long      orderno;
	long      pt_date;
	long      pt_trace_no;
	char      or_br_no[15];
	char      sndrcvflag[6];
	double    tx_amt;
	char      con_marking[12];
	char      bor_lend[6];
	char      main_acc_no[33];
	char      main_acc_nm[61];
	char      gd_acc_no[33];
	char      snd_acc_no[33];
	char      note_type[6];
	char      note_no[18];
	char      tx_br_no[7];
	char      teller[8];
	long      tx_date;
	long      trace_no;
	char      com_stat[3];
	char      batch_detail[3];
	char      chrgflag[3];
	char      chrg_ind[3];
	double    chrg_amt;
	char      chrgacno[33];
	char      feeaccno[33];
	long      com_pt_date;
	long      com_swno;
	char      gz_br_no[7];
	char      gz_acct_no[33];
	char      gz_reasen[4];
	char      com_flag[3];
	char      com_result[61];
};
#endif 
