#ifndef __chnl_self_trade_CH__
#define __chnl_self_trade_CH__
struct chnl_self_trade_c{
	char      rowid[20];
	long      tx_date;
	long      tx_time;
	long      trace_no;
	char      cur_no[3];
	char      ac_no[21];
	char      ac_no1[21];
	char      tx_code[5];
	char      tx_br_no[6];
	char      opn_br_no[6];
	char      tel[5];
	char      ttyp[2];
	char      ttyn[21];
	char      sh_opn_br_no[6];
	char      spcd[21];
	char      bbmk[5];
	char      sctp[3];
	long      dz_date;
	long      stra;
	long      strb;
	long      premise_date;
	long      premise_no;
	double    premise_amt;
	double    tx_amt;
	double    sl_sxamt;
	double    fk_sxamt;
	double    dz_sxamt;
	char      dz_flag[2];
	char      ct_ind[2];
	char      info_source[2];
	char      deal_flag[2];
	char      brf_no[6];
	char      add_ind[2];
	char      batch_flag[2];
	char      stat[2];
	char      brf_dscp[51];
	char      tt_no[5];
};
#endif 
