#ifndef __chnl_tx_detl_CH__
#define __chnl_tx_detl_CH__
struct chnl_tx_detl_c{
	char      rowid[20];
	char      tx_code[7];
	char      syscode[7];
	char      chnl_type[2];
	long      tx_date;
	char      tx_time[27];
	long      trace_no;
	long      trace_cnt;
	long      pt_date;
	long      pt_trace_no;
	long      wt_date;
	char      orderno[13];
	char      or_br_no[15];
	char      sndrcvflag[5];
	char      ac_no[33];
	char      ac_name[61];
	char      add_ind[2];
	char      ct_ind[2];
	double    tx_amt;
	char      df_br_no[13];
	char      df_ac_no[33];
	char      df_name[61];
	char      df_id_type[4];
	char      df_id_no[21];
	char      txnum[5];
	char      yw_type[6];
	char      dz_ind[3];
	char      filler1[61];
	char      filler2[61];
	char      filler3[61];
	char      filler4[61];
};
#endif 
