#ifndef __cif_cop_inf_CH__
#define __cif_cop_inf_CH__
struct cif_cop_inf_c{
	char      rowid[20];
	long      cif_no;
	long      reg_date;
	char      reg_country[4];
	double    reg_fund;
	char      cur_no[3];
	char      crd_no[21];
	char      units_license[21];
	char      g_tax_no[21];
	char      d_tax_no[21];
	char      credit_no[17];
	char      license[21];
	char      eco_attri[2];
	char      ent_attri[2];
	char      credit[2];
	char      region[2];
	char      supervior[51];
	char      director[51];
	char      belong_bank[2];
	char      belong_stat[2];
	char      mana_orga_moda[2];
	char      bd_corp_orga_moda[2];
	char      corp_size[2];
	char      corp_act_mode[2];
	double    paicl_up_capital;
	char      corp_mana_sts[2];
	char      ap_qualife[21];
	char      artificial_person[21];
	char      ap_id[21];
	char      cif_scopes[3];
};
#endif 
