#ifndef __fn_parm_CH__
#define __fn_parm_CH__
struct fn_parm_c{
	char      rowid[20];
	char      prdt_code[21];
	char      title[61];
	char      prdt_type[2];
	char      intst_type[2];
	long      beg_date;
	long      end_date;
	long      ic_date;
	long      mtr_date;
	long      return_date;
	char      term_type[2];
	long      term;
	char      cif_type[2];
	char      cur_no[3];
	char      chnl_type[5];
	char      risk_lvl[2];
	char      invest_type[2];
	double    rate;
	double    fct_rate;
	char      float_rate_flag[2];
	double    capital_percent;
	double    chrg_rate;
	double    trust_rate;
	double    manage_rate;
	double    profit_rate;
	double    min_amt;
	double    sale_amt;
	double    unit_amt;
	double    add_amt;
	double    per_min_amt;
	double    com_min_amt;
	char      cancel_flag[2];
	char      redempt[2];
	double    redempt_chrg;
	char      quota_flag[3];
	char      per_ac_no[25];
	char      com_ac_no[25];
	char      stat[2];
	char      tel1[7];
	char      tel2[7];
};
#endif 
