#ifndef __fn_reg_CH__
#define __fn_reg_CH__
struct fn_reg_c{
	char      rowid[20];
	long      tx_date;
	long      trace_no;
	char      tx_br_no[6];
	char      pact_no[21];
	char      prdt_code[21];
	char      ac_no[25];
	long      ac_id;
	long      ac_seqn;
	char      cif_type[2];
	char      ct_ind[2];
	char      chnl_type[5];
	long      count;
	double    tx_amt;
	double    redempt_amt;
	double    return_capital;
	double    flt_radio;
	double    return_rate;
	double    intst;
	long      ic_date;
	long      end_date;
	double    fct_intst;
	double    profit_amt;
	double    fct_profit_amt;
	char      profit_flag[2];
	char      brf[21];
	char      sts[2];
	double    amt1;
	double    amt2;
	long      date1;
	long      date2;
	long      pay_date;
	long      pay_trace_no;
	long      return_date;
	long      return_trace_no;
	char      tel[7];
	char      mang[7];
	char      agent_id_type[2];
	char      agent_id[21];
	char      agent_name[61];
	char      filler[61];
};
#endif 
