#ifndef __gl_note_CH__
#define __gl_note_CH__
struct gl_note_c{
	char      rowid[20];
	char      br_no[6];
	char      note_type[4];
	long      date;
	double    cr_bal;
	double    lcd_bal;
	long      rdd_cnt;
	long      rcd_cnt;
	double    rdd_amt;
	double    rcd_amt;
	double    tdcr_bal;
	long      tddr_cnt;
	long      tdcr_cnt;
	double    tddr_amt;
	double    tdcr_amt;
	double    mcr_bal;
	long      mdr_cnt;
	long      mcr_cnt;
	double    mdr_amt;
	double    mcr_amt;
	double    qcr_bal;
	long      qdr_cnt;
	long      qcr_cnt;
	double    qdr_amt;
	double    qcr_amt;
	double    ycr_bal;
	long      ydr_cnt;
	long      ycr_cnt;
	double    ydr_amt;
	double    ycr_amt;
};
#endif 
