#ifndef __gl_oprt_dyn_CH__
#define __gl_oprt_dyn_CH__
struct gl_oprt_dyn_c{
	char      rowid[20];
	long      date;
	char      br_no[6];
	double    cr_de_bal;
	double    ys_de_bal;
	double    yb_de_bal;
	double    cr_de_bal1;
	double    ys_de_bal1;
	double    yb_de_bal1;
	double    cr_de_bal2;
	double    ys_de_bal2;
	double    yb_de_bal2;
	double    cr_de_bal3;
	double    ys_de_bal3;
	double    yb_de_bal3;
	double    cr_de_bal4;
	double    ys_de_bal4;
	double    yb_de_bal4;
	double    cr_de_bal5;
	double    ys_de_bal5;
	double    yb_de_bal5;
	double    cr_de_bal6;
	double    ys_de_bal6;
	double    yb_de_bal6;
	double    cr_ln_bal;
	double    ys_ln_bal;
	double    yb_ln_bal;
	double    cr_ln_bal1;
	double    ys_ln_bal1;
	double    yb_ln_bal1;
	double    cr_ln_bal2;
	double    ys_ln_bal2;
	double    yb_ln_bal2;
	double    cr_ln_bal3;
	double    ys_ln_bal3;
	double    yb_ln_bal3;
	double    cr_ln_bal4;
	double    ys_ln_bal4;
	double    yb_ln_bal4;
	double    cr_ln_bal5;
	double    ys_ln_bal5;
	double    yb_ln_bal5;
};
#endif 
