#ifndef __hv_fzfhtr_CH__
#define __hv_fzfhtr_CH__
struct hv_fzfhtr_c{
	char      rowid[20];
	char      or_br_no[13];
	char      orderno[9];
	long      tx_date;
	long      wt_date;
	char      br_no[8];
	char      hv_fzfhtr_sts[2];
	char      cmtno[4];
	long      tx_time;
	long      trace_no;
	char      pay_qs_no[13];
	char      ac_br_no[13];
	char      cash_qs_no[13];
	long      o_tx_date;
	char      o_or_br_no[13];
	char      o_ac_br_no[13];
	char      o_orderno[9];
	char      o_cur_ind[4];
	double    o_tx_amt;
	char      o_cmtno[4];
	char      o_tx_type[2];
	char      sendco[5];
	char      receco[5];
	long      req_date;
	char      req_br_no[13];
	char      req_content[256];
	char      req_orderno[9];
	long      res_date;
	char      res_br_no[13];
	char      res_content[256];
	char      res_orderno[9];
	char      res_sts[2];
	char      addid[9];
	char      refno[21];
	char      hv_prt_ind[11];
	char      hv_brf[61];
	char      tel[7];
	char      lw_ind[2];
	long      o_trace_no;
};
#endif 
