#ifndef __ln_auth_CH__
#define __ln_auth_CH__
struct ln_auth_c{
	char      rowid[20];
	char      pact_no[21];
	char      name[61];
	long      time_lmt;
	double    amt;
	double    rate;
	char      pay_ac_no[20];
	long      pay_ac_id;
	char      save_ac_no[20];
	long      save_ac_id;
	char      save_mdm_code[5];
	char      sts[2];
	double    intst_amt;
	double    over_rate;
	double    cmpd_rate;
	double    fine_rate;
	char      prdt_no[4];
	long      mtr_date;
	long      cif_no;
	char      type[3];
	char      ln_type[2];
	double    flt_rate;
	long      beg_date;
	char      flt_flag[2];
	char      intst_type[2];
	char      chg_ac_sts[2];
	char      repay_type[2];
	char      trust_no[21];
	char      bail_cif_no[51];
	char      cms_tx_br_no[6];
	char      cms_tel[6];
	char      filler1[21];
	char      filler2[21];
};
#endif 
