#ifndef __lv_dsfsendlist_CH__
#define __lv_dsfsendlist_CH__
struct lv_dsfsendlist_c{
	char      rowid[20];
	char      packid[9];
	char      orderno[9];
	long      wt_date;
	char      tx_type[6];
	char      or_br_no[13];
	char      ac_br_no[13];
	char      msg_len[9];
	char      add_tag[101];
	char      o_packid[9];
	char      o_orderno[9];
	long      o_wt_date;
	char      o_tx_type[6];
	char      sts[3];
	char      content[61];
	char      re_packid[9];
	char      re_orderno[9];
	long      re_wt_date;
	char      re_or_br_no[13];
	char      re_ac_br_no[13];
	char      re_msg_len[9];
	char      re_addit[92];
	char      repstat[3];
	char      re_content[61];
};
#endif 
