#ifndef __mo_invest_CH__
#define __mo_invest_CH__
struct mo_invest_c{
	char      rowid[20];
	char      pact_no[21];
	char      bkrl_code[4];
	char      br_no[6];
	long      ac_id;
	long      lx_ac_id;
	char      invest_type[2];
	char      ticket_type[21];
	char      intst_type[2];
	long      cnt;
	long      isuue_date;
	long      term;
	double    par_bal;
	double    buy_amt;
	long      abate_ac_id;
	double    abate_amt;
	long      overflow_ac_id;
	double    overflow_amt;
	double    pre_intst;
	long      buy_date;
	double    rate;
	double    flt_rate;
	long      mtr_date;
	double    sol_amt;
	long      sol_date;
	double    singl_feeval;
	double    sol_feeval;
	long      wrk_date;
	long      trace_no;
	char      sts[2];
	char      tel[5];
	char      chk[5];
	char      auth[5];
};
#endif 
