#ifndef __mo_ppe_CH__
#define __mo_ppe_CH__
struct mo_ppe_c{
	char      rowid[20];
	char      ppeno[20];
	char      ppename[81];
	char      opdate[9];
	char      type[2];
	char      spemodel[21];
	double    quant;
	double    oriamt;
	char      chgactno[20];
	double    chgamt;
	double    depramtyear;
	char      depractno[20];
	double    depramtttl;
	double    remamt;
	char      deprstat[2];
	char      stat[2];
	char      moden[2];
	double    remainratio;
	char      period[2];
	double    term;
	double    usedterm;
	double    usedquant;
	double    ttlquant;
	long      ttlcnt;
	double    deprradio;
	char      asstype[2];
	char      deprtype[2];
	char      placebrno[8];
	char      addr[201];
	char      ppestat[21];
	char      chkdate[9];
	char      brf[201];
};
#endif 
