#ifndef __od_mst_CH__
#define __od_mst_CH__
struct od_mst_c{
	char      rowid[20];
	long      ac_id;
	long      ac_seqn;
	char      opn_br_no[6];
	char      prdt_no[4];
	double    bal;
	double    drt_bal;
	double    cur_bal;
	double    intst_amt;
	double    intst_bal;
	double    drt_intst_bal;
	double    cash_bal;
	double    ys_bal;
	double    hst_bal;
	double    intst_acm;
	double    drt_intst_acm;
	double    max_bal;
	double    cash_max_bal;
	double    min_pay_amt;
	double    min_pay_ratio;
	long      lst_date;
	long      hst_cnt;
	long      hst_pg;
	char      ac_sts[2];
	long      pay_ac_id;
	long      pay_ac_seqn;
	char      mac[17];
};
#endif 
