SHELL	=	sh

#Q64     =   -q64
CC		=	cc $(Q64) -g
LD		=	ld

RM		=	@rm -f
MV		=	@mv
CP		=	@cp
ECHO	=	@echo


# paths and flags
 
BIN	= $(HOME)/bin
LIBDIR  = $(HOME)/lib

INC	= -I$(HOME)/src/incl_c -I$(HOME)/src/incl_ec -I$(HOME)/src/incl_pub
CLIB	= -L$(HOME)/lib -L.
CFLAGS	= $(INC) $(CLIB)
#LIBAPL  = -lbaltcp -lcomm -lbase -lcom -lpubdb -lpubdb_m -lc -lm
LIBAPL  = -lbaltcp -leod -lcomm -lbase -lcom -lpubdb -lpubdb_m -lc -lm

OBJS =  sp9103.so sp9105.so sp9107.so sp9109.so sp9111.so sp9601.so sp9603.so sp9605.so sp9607.so \
	sp9613.so sp9615.so sp9619.so sp9621.so spG001.so \
	spG501.so spwl1.so \
	sp9101.so sp9104.so sp9106.so sp9108.so sp9110.so sp9600.so sp9602.so \ 
	sp9604.so sp9606.so sp9612.so sp9614.so sp9616.so sp9620.so sp9632.so spG002.so spwl.so
TARGET	= \
		$(BIN)/lib.so

all: Mstart $(TARGET) Mcomplete
 
Mstart:
	$(ECHO)
	$(ECHO) "MAKE lib.so:$(TARGET) ..."
	$(ECHO)

Mcomplete:
	$(ECHO)
	$(ECHO) "MAKE lib.so:$(TARGET) completed."
	$(ECHO)
 
$(TARGET):$(OBJS)


# implicit
 
.SUFFIXES: .so .c
 
.c.so:
	$(CC) $(CFLAGS) -c $*.c
	$(CC) -brtl -G -o $@ $(CFLAGS) $*.o 
#	$(CC) -brtl -qmkshrobj  -o $@ $(CFLAGS) $*.o -L$(LIBDIR) $(LIBAPL) 
	mv $(*F).so $(LIBDIR)
	$(RM) $(*F).o

.c:
	$(CC) -G -o $@ $(CFLAGS) $*.c $(LIBAPL)
	mv *.so $(LIBDIR)

# default
 
#.DEFAULT:
 
# clearing object codes
 
clean: cleanup
	$(RM) $(TARGET)
 
cleanup:
	$(RM) $(OBJS)
 
# dependencies

