drop index hv_fzfhtr_idx;
drop  table hv_fzfhtr;
create table hv_fzfhtr(
	or_br_no varchar2(12),
	orderno varchar2(8),
	tx_date number(9),
	wt_date number(9),
	br_no varchar2(7),
	hv_fzfhtr_sts varchar2(1),
	cmtno varchar2(3),
	tx_time number(9),
	trace_no number(9),
	pay_qs_no varchar2(12),
	ac_br_no varchar2(12),
	cash_qs_no varchar2(12),
	o_tx_date number(9),
	o_or_br_no varchar2(12),
	o_ac_br_no varchar2(12),
	o_orderno varchar2(8),
	o_cur_ind varchar2(3),
	o_tx_amt number(15,2),
	o_cmtno varchar2(3),
	o_tx_type varchar2(1),
	sendco varchar2(4),
	receco varchar2(4),
	req_date number(9),
	req_br_no varchar2(12),
	req_content varchar2(255),
	req_orderno varchar2(8),
	res_date number(9),
	res_br_no varchar2(12),
	res_content varchar2(255),
	res_orderno varchar2(8),
	res_sts varchar2(1),
	addid varchar2(8),
	refno varchar2(20),
	hv_prt_ind varchar2(10),
	hv_brf varchar2(60),
	tel varchar2(6),
	lw_ind varchar2(1),
	o_trace_no number(9)
)tablespace users;
create	 unique index hv_fzfhtr_idx on hv_fzfhtr( or_br_no,wt_date,orderno,cmtno,trace_no)tablespace indx;
